@startuml Kafka Context Integration
title Kafka Context / Integration Diagram\nИнтеграция SAP FI и TRM через Apache Kafka

top to bottom direction
skinparam componentStyle rectangle
skinparam linetype ortho

 package "Producers\nИсточники" {
        component "Open Vendor Item (FI-AP)\nОткрытая позиция кредитора" as OVI
        component "Open Customer Item (FI-AR)\nОткрытая позиция дебитора" as OCI
        component "Taxes\nНалоги" as Tax
        component "Payroll\nЗарплата" as Proll
        component "Contract Payment\nПлатёж по договору" as ContractPay
        component "Manual Request\nРучная заявка" as ManualPay
    }

node "Apache Kafka Cluster" as KAFKA {
    queue "payment.demand\n4 partitions" as DEMAND
   
    queue "payment.demand.DLQ\nОшибочные события" as DLQ

    queue "paymentStatus.demand\n4 partitions" as DemandReturn
    DEMAND -[hidden]down-> DLQ
    DLQ -[hidden]down-> DemandReturn
}

package "Treasury System (TRM)\nКазначейская система" {
    component "Demand Consumer\nconsumer group: trm-demand" as CONSUMER
}


OVI --> DEMAND : один key для всех сообщений от одного заказа, чтобы попадать в одну партицию
OCI --> DEMAND 
Tax --> DEMAND
Proll --> DEMAND
ContractPay --> DEMAND
ManualPay --> DEMAND

DEMAND ..> DLQ : ошибка после retry
DEMAND -down-> CONSUMER

CONSUMER --> DemandReturn
DemandReturn --> OVI
DemandReturn --> OCI
DemandReturn --> Tax
DemandReturn --> Proll
DemandReturn --> ContractPay
DemandReturn --> ManualPay

/'note bottom of DEMAND
  Одно событие отражает одну FI-потребность.
  Порядок гарантирован только в пределах одной партиции.
end note

note bottom of REQUEST
  Одна исходная потребность создаёт одну заявку в TRM.
  Повторы событий обрабатываются идемпотентно.
end note
'/

legend right
  Producer: SAP FI через Outbox / Event Publisher
  Consumer: TRM Demand Consumer
  Основной топик: payment.demand
  Семантика доставки: at-least-once
endlegend

@enduml
